on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  error-enwrap:
    runs-on: ubuntu-latest
    steps:
      # 1 – Get the full history so we can push back
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        # important for pushes

      # 2 – Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3 – Generate wrapped code
      - name: Run stdError wrapping script
        run: node ./Tools/VBA-stdError-Wrapper/main.js

      # 4 – Commit **everything** and force-push to stdError-Wrapped
      - name: Commit and push to stdError-Wrapped
        run: |
          git config --global user.name  "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add -A
          git commit -m "Wrapped latest changes in stdError sentries" || echo "No changes to commit"

          # force-update the remote branch with whatever HEAD is now
          git push origin HEAD:refs/heads/stdError-Wrapped --force
